version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      valkey:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://valkey:6379
    ports:
      - "3030:3030"
    networks:
      - valkey_network
    env_file:
      - .env
  valkey:
    container_name: valkey
    hostname: valkey
    networks:
      - valkey_network
    image: valkey/valkey:latest
    volumes:
      #      - ./conf/valkey.conf:/etc/valkey/valkey.conf
      - valkey_data:/data
    command: valkey-server
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

volumes:
  valkey_data:
networks:
  valkey_network:
    driver: bridge