version: '3.7'

services:
  valkey:
    container_name: valkey
    hostname: valkey
    image: valkey/valkey:latest
    volumes:
      - ./conf/valkey.conf:/etc/valkey/valkey.conf
      - ./data:/data
    command: valkey-server /etc/valkey/valkey.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
  checkbox:
    container_name: checkbox
    hostname: checkbox
    depends_on:
      - valkey
    image: mrtnschwz/checkboxes
    environment:
      REDIS_URL: "redis://valkey"
      SERVER_PORT: 3030
      REDIS_BITMAP_NAME: "mybitmap"
      NUMBER_OF_CHECKBOXES: "1000"
    ports:
      - "3030:3030"

networks:
  valkey_network:
    driver: bridge